export const endponts = {
    login: 'auth/login',
    school: 'schools/school',
    schoolProfile: 'school/profile',
    student:'school/student',
    getAllStudents: 'school/students',
    teacher: 'schools/teachers',
    parent: 'schools/guardians',
    class: 'schools/classes',
    singleClass: 'schools/class',
    section: 'schools/sections',
    invitation: 'auth/invite',
    authRegister: 'auth/register',
    departments: '/schools/departments',
    sessions: '/session',
    subject: '/schools/subjects',
    timeTable: '/schools/routines',
    emailSubscribe:'auth/email',
    fileUpload: '/file-upload/signed-url/',
    uploadFileName:'/file-upload/uploads',
    getSkill:'teacher/skill'
}