export const endponts = {
    login: 'auth/login',
    school: 'schools/school',
    schoolProfile: 'school/profile',
    student: 'school/student',
    getAllStudents: 'school/students',
    teacher: 'school/teacher',
    parent: 'school/guardian',
    class: 'class',
    singleClass: 'schools/class',
    section: 'section/',
    invitation: 'auth/invite',
    authRegister: 'auth/register',
    departments: 'schools/departments',
    sessions: 'session',
    subject: 'schools/subjects',
    timeTable: 'schools/routines',
    emailSubscribe: 'auth/email',
    fileUpload: 'file-upload/signed-url/',
    uploadFileName: 'file-upload/uploads',
    register: 'auth/register',
    studentEdu: 'student/qualification',
    registerPhone: 'user/phone/',
    verifyOtp: 'user/verify/phone/',
    teahcerSkill: 'teacher/skill',
    // teahcerExperience: 'teacher/experience',
    teahcerEducation: 'teacher/qualification',
    techerExp: 'teacher/experience',
    teacherBio: 'auth/teacher/bio/',
    teacherFileUpload: 'file-upload/uploads/documents',
    parentChildAdd: 'guardian/children',
    forgotEmail: 'auth/forget/password',
    resetPassword: 'auth/reset/password/',
};

export const studentsEndpoints = {
    getFeatureTeacher: 'student/feature/teacher',
    getUpcomingSessions: 'student/upcoming/session',
    getPreviousSessions: 'student/previous/session'
}
