import React from 'react';
import {
    Dashboard as DashboardIcon,
    AccountBalanceWallet,
    Settings,
    AccountCircle,
    School,
    Book,
} from '@material-ui/icons';

export const NavigationMenu: any[] = [
    {
        menuName: 'Dashboard',
        icon: <DashboardIcon />,
        isExpandable: false,
        isOpen: false,
        menuList: [],
        routeName: '/dashboard',
    },
    {
        menuName: 'Users',
        icon: <AccountCircle />,
        isExpandable: true,
        menuList: [
            {
                menuName: 'Admin',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/admin',
            },
            {
                menuName: 'Student',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/students',
            },

            {
                menuName: 'Teacher',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/teachers',
            },
            {
                menuName: 'Parent',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/parents',
            },
            {
                menuName: 'Staff',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/staff',
            },
        ],
        routeName: '',
    },
    {
        menuName: 'Academic',
        icon: <School />,
        isExpandable: true,
        menuList: [
            {
                menuName: 'Daily Attendance',
                isExpandable: false,
                menuList: [],
                routeName: '/daily-attendance',
            },
            {
                menuName: 'Class Routien',
                isExpandable: false,
                menuList: [],
                routeName: '/class-routien',
            },
            {
                menuName: 'Subject',
                isExpandable: false,
                menuList: [],
                routeName: '/subject',
            },
            {
                menuName: 'Syllabus',
                isExpandable: false,
                menuList: [],
                routeName: '/syllabus',
            },
            {
                menuName: 'class',
                isExpandable: false,
                menuList: [],
                routeName: '/class',
            },
            {
                menuName: 'class Room',
                isExpandable: false,
                menuList: [],
                routeName: '/class-room',
            },
            {
                menuName: 'department',
                isExpandable: false,
                menuList: [],
                routeName: '/department',
            },
            {
                menuName: 'Event Calender',
                isExpandable: false,
                menuList: [],
                routeName: '/event-calender',
            },
        ],
        routeName: '',
    },
    {
        menuName: 'Exam',
        icon: <Book />,
        isExpandable: true,
        routeName: '',
        menuList: [
            {
                menuName: 'Marks',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/marks',
            },
            {
                menuName: 'Exams',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/exams',
            },
            {
                menuName: 'Grades',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/grades',
            },
            {
                menuName: 'Promotion',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/promotion',
            },
        ],
    },
    {
        menuName: 'Accounts',
        icon: <AccountBalanceWallet />,
        isExpandable: true,
        routeName: '',
        menuList: [
            {
                menuName: 'Student Fee Manager',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/studen-free-manager',
            },
            {
                menuName: 'Expense Category',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/expense-category',
            },
            {
                menuName: 'Expense Manager',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: '/expense-manager',
            },
        ],
    },
    {
        menuName: 'Settings',
        icon: <Settings />,
        isExpandable: true,
        menuList: [
            {
                menuName: 'System Settings',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: 'system-settings',
            },
            {
                menuName: 'Website Settings',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: 'website-settings',
            },
            {
                menuName: 'School Settings',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: 'school-settings',
            },
            {
                menuName: 'Payment Settings',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: 'payment-settings',
            },
            {
                menuName: 'SMTP Settings',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: 'smtp-settings',
            },
            {
                menuName: 'About',
                isExpandable: false,
                isOpen: false,
                menuList: [],
                routeName: 'about',
            },
        ],
        routeName: '',
    },
];