export const HOMEWORK_PENDING = 'STUDENT_MODULE/HOMEWORK_PENDING';
export const HOMEWORK_SUCCESS = 'STUDENT_MODULE/HOMEWORK_SUCCESS';
export const HOMEWORK_FAILURE = 'STUDENT_MODULE/HOMEWORK_FAILURE';
