export const SCHOOL_LIST = 'SCHOOL_LIST';
export const VIDEO_LIST = "VIDEO_LIST";
export const ADMIN_TEACHER_LIST = "ADMIN_TEACHER_LIST";
export const ADMIN_STUDENT_LIST = "ADMIN_STUDENT_LIST";
export const ADMIN_PARENTS_LIST = "ADMIN_PARENTS_LIST";
