export const TEACHER_INFO = "TEACHER_INFO";
export const TEACHER_LIST = "TEACHER_LIST";
export const TEACHER_DETAILS = "TEACHER_DETAILS";
export const TEACHER_DATA="TEACHER_DATA";
export const GET_TEACHER_SKILLS="GET_TEACHER_SKILLS";
export const ADD_TEACHER_SKILLS="ADD_TEACHER_SKILLS";
